### PR TITLE
Cypress adding audience and router wrappers

### PR DESCRIPTION
**Pull request by mdapim**
- added audience context and browser router to header and topic cypress tests

### CODE REVIEW

**Review by Mariam-mohamed110 — APPROVED** [review]

**Review by s-dilip — APPROVED** [review]
Ran all the cypress tests on my device and they all pass. Nicely done!

**Review by bp289 — APPROVED** [review]

**Comment by mdapim** [comment]
Great idea @DomVinyard, @yuna-iwata  also suggested this, we have added the yml file from [Add Cyprus tests to GitHub Actions workflow#69](https://github.com/Sigma-Labs-XYZ/explain-ai/issues/69) into this branch to check it all works, all the tests pass should be good to merge, are we alright to keep it on here rather than raising a separate branch for this?

**Comment by DomVinyard** [comment]
> Great idea @DomVinyard, @yuna-iwata also suggested this, we have added the yml file from [Add Cyprus tests to GitHub Actions workflow#69](https://github.com/Sigma-Labs-XYZ/explain-ai/issues/69) into this branch to check it all works, all the tests pass should be good to merge, are we alright to keep it on here rather than raising a separate branch for this?

yes absolutely, only think to keep in mind for future is that it's best to turn the PR into a draft PR while you continue working on it 👍

**Review by DomVinyard — DISMISSED** [review]
test request

**Pull request merged**
