### PR TITLE
Bug/header#101

### PR DESCRIPTION
**Pull request by yuna-iwata**
- logo fully visible between 400-600px 
- cypress header tests adjusted 
- "Like I'm" text removed for under $small-phone-width: 330px

### CODE REVIEW

**Comment by s-dilip** [comment]
Are those **.mp4** files needed in **cypress/videos** directory? If not, they can be deleted.

**Review by mdapim — APPROVED** [review]
Looks good and works well, like how it snaps together during changes

**Comment by DomVinyard** [comment]
> Are those **.mp4** files needed in **cypress/videos** directory? If not, they can be deleted.

probably best added to .gitignore

**Review by DomVinyard — APPROVED** [review]
Looks good once the conflicts are sorted

**Pull request merged**
