### PR TITLE
relcard styling issues fixed

### PR DESCRIPTION
**Pull request by yuna-iwata**
images fixed

### CODE REVIEW

**Review by DomVinyard — APPROVED** [review]
Looks good to me

**Comment by Ademsk1** [comment]
Looks good to me! Let's merge!

**Comment by Ademsk1** [comment]
This isn't passing the test:
```
Test for API render on success › Clicking on a relation card should take you to the correct topic
```
or 
```
 Clicking on a relation card should take you to the correct topic
```
Can you try on your branch? I've been having trouble all day with Git. @yuna-iwata

**Comment by yuna-iwata** [comment]
> There is still a slight margin on the relation cards image


> Should be fixed now for some reason ml-5 was deleted

**Review by s-dilip — APPROVED** [review]

**Review by bp289 — APPROVED** [review]

**Pull request merged**
